### ISSUE TITLE
s3put.sh and s3get.sh not working for AWS Signature Version 4.

### ISSUE THREAD

**Issue by xuwang** [xuwang/kube-aws-terraform#2]
resources/vault/artifacts/upload/scripts/s3put.sh and s3get.sh need to be fixed for
AWS Signature Version 4.

**Comment by xueshanf** [comment]
Upgraded s3get.sh and s3put.sh to support S3 signature v4 authentication. https://github.com/xuwang/kube-aws-terraform/commit/4fb20048abfb046bea37155799ea5720dc5d541f
