### ISSUE TITLE
docker: invalid reference format

### ISSUE THREAD

**Issue by stiks** [xuwang/kube-aws-terraform#20]
Trying to setup cluster in eu-west-2, for some reason it's not going anywhere
docker: 17.06.2-ce, build cec0b72
terraform: v0.9.2

```
$ make cluster
cd resources/vpc; make apply
/hostedzone/ZILEF0VJIN46T
set remote state to s3://91337091-kuster-terraform/vpc.tfstate
Creating bucket for remote state ...
make_bucket: 913237091-kuster-terraform
docker: invalid reference format.
See 'docker run --help'.
make[1]: *** [init] Error 125
make: *** [vpc] Error 2
```

**Comment by xueshanf** [comment]
@stiks there were some code changes in the time frame of your build... could you try to update the repo and see if this is repeatable?

**Comment by stiks** [comment]
I've updated repo today morning, still the same. I've tried even clean install + env file. Problem stays the same

**Comment by xueshanf** [comment]
@stiks what OS are you run the terraform on? Could you turn on verbose by removing the @ sign in *resources/common/common.mk* file: 
```
apply: init ## terraform apply
	@${TF_APPLY}
```
That should show exactly what make command is running.

**Comment by xueshanf** [comment]
@stiks BTW, I am on Docker for Mac, 17.09.0-ce-rc1. Your's version should work too. Mind updating and restarting docker for mac?  We use container to run Terraform to make sure same Terraform version is used, not depending on what's installed on the machine.

**Comment by stiks** [comment]
Removing @ had no difference. 

It's look like when script is trying to call: 
```
$ docker run -i --rm --env-file=/Users/stiks/tmp/kube/resources/vpc/build/tf.env 
-v=/Users/stiks/.aws:/root/.aws -v=/Users/stiks/tmp/kube/resources/vpc/build:/build 
-w=/build hashicorp/terraform:"~>0.9.1"
```
I get: 
```
docker: invalid reference format.
See 'docker run --help'.
```
Changing TF_VERSION to "0.9.1" instead of "~>0.9.1" resolve issue

**Comment by stiks** [comment]
On the first run:
