### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by stiks** [xuwang/kube-aws-terraform#23]
dashboard yaml is no longer available on URL:
https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

I should be https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml (I believe)

**Comment by xuwang** [comment]
@stiks updated with https://github.com/xuwang/kube-aws-terraform/commit/309038e56a468ea92d249682a007c838e8927f6c. Thanks!
