### ISSUE TITLE
make ui gives errors

### ISSUE THREAD

**Issue by Jamie-BitFlight** [xuwang/kube-aws-terraform#25]
When running
make ui
it gives errors, as it seems to have a broken configuration.

I changed it to this, and it now builds, but I've only been working on this repo for about an hour so I'm not sure if it has broken anything else?
`./resources/add-ons/Makefile`
```
 85 .PHONY: dashboard
 86 dashboard: kube-system-admin-role-binding ## Start dashboard
 87   @if ! kubectl get pods -n kube-system |grep kubernetes-dashboard |grep Running &> /dev/null ; \
 88   then \
 89     kubectl apply -f ${KUBERNETES_DASHBOARD} ; \
 90   else \
 91     kubectl get svc,pods -n kube-system -l k8s-app=kubernetes-dashboard ; \
 92   fi
```

**Comment by xueshanf** [comment]
@Jamie-BitFlight The target that dashboard depends on was changed from `re-config` to `kube-reconfig`. It was fixed in Makefile. It did not impact dashboard provision without this target  as long as you are working on the same cluster.

**Comment by xueshanf** [comment]
@Jamie-BitFlight close now. let us know if you still have issues. the repo is now updated to support both etcd2 and etcd3, you might want to start from new repo.
