### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by agentbond007** [xuwang/kube-aws-terraform#26]
Make Add-ons produces YAML issue
error: unable to read URL "https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml", server reported 404 Not Found, status code=404
make[1]: *** [dashboard] Error 1
make: *** [add-ons] Error 2

Looks like Github repo kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml   changed.

**Comment by xueshanf** [comment]
@agentbond007 This should be fixed by https://github.com/xuwang/kube-aws-terraform/commit/309038e56a468ea92d249682a007c838e8927f6c, no?

**Comment by agentbond007** [comment]
Yes.  Thank you xue. 🙏🏻
