### ISSUE TITLE
kube admin certs mis-match in multi-master cluster

### ISSUE THREAD

**Issue by xuwang** [xuwang/kube-aws-terraform#28]
In a multi-master cluster, `make kube-config` may get admin.pem and admin-key.pem from different masters because the api is behind loadbalancer, resulting key mis-match error on kubectl calls.

We need to bundle  admin.pem, admin-key.pem, and ca in one file and get it from master in one call.

See bug at: https://github.com/xuwang/kube-aws-terraform/blob/master/resources/add-ons/Makefile#L37

**Comment by xueshanf** [comment]
Resolved by https://github.com/xuwang/kube-aws-terraform/commit/1af116d73b18e4c00b5f8aa69c5ce7967f1114b7.
