### ISSUE TITLE
aws iam get-user fails when using  iam roles

### ISSUE THREAD

**Issue by llinder** [xuwang/kube-aws-terraform#5]
When using IAM roles in AWS CLI config,  `aws iam get-user` require --user-name flag.

Example profile configuration that will cause the failure:
```
[profile cp-identity-useast2]
output = json
region = us-east-2

[profile cp-telemetry-useast2]
source_profile = cp-identity
role_arn = arn:aws:iam::1234567:role/ident-company_telemetry-architect
region = us-east-2
```

**Comment by xueshanf** [comment]
@llinder I think this should work for both role-based and iam user based profile:
```
$ aws --profile <profile>  sts get-caller-identity --output text --query 'Account'
```
We can use user local userid for the purpose of book-keeping. I think the only place we use username is in the vpc tag field, which isn't important anyway.

We definitely need accountid that is used everywhere.

**Comment by llinder** [comment]
That does indeed solve the problem for retrieving the account id.  Thanks for the suggestion!

**Comment by llinder** [comment]
@xueshanf do you think its worth pursuing a way to make this repository compatible with iam assume roles?  I can make a PR with my changes that work for me.  I'm not sure they will be easy to add but am willing to share if there is interest.

**Comment by xueshanf** [comment]
@llinder I was working on this today and just pushed a bunch of changes. https://github.com/xuwang/kube-aws-terraform/commit/80d1c9fc6b34c8b5abd33eb7243e2992be3cde6d should make the iam assuming role configuration work - I simply replaced all `aws iam get-user` with `aws sts ..` command. If this doesn't work for you, please do make a PR! Thanks so much!

**Comment by llinder** [comment]
@xueshanf here is a PR that adds the remaining config to make role based authentication work with Terraform.  Note I'm not sure what to do about the role entries in `common.tf`.  Looking for ideas on that one before this is usable without role based authentication.

https://github.com/xuwang/kube-aws-terraform/pull/6

**Comment by xueshanf** [comment]
@llinder tested with using both assume role and regular IAM user in provider and tf s3 backend configure. close #6. Thanks!
