### ISSUE TITLE
Close port 22 by default

### ISSUE THREAD

**Issue by xueshanf** [xuwang/kube-aws-terraform#8]
Make ssh security rule ephemeral rather permanent.

* `make ssh` will allow ssh to a machine by altering security group rules to enable/disable ssh from the operator's machine IP. 
* `make remote-ssh` will open ssh rule temporarily to operator's machine IP so remote ssh can be used to view logs, uptime, load etc for troubleshooting. 
* `make open-ssh` and `make close-ssh` can be used to open or close port 22 to a machine, source from operator's IP. 

This allows relatively securer operation without a bastion host yet.

**Comment by xuwang** [comment]
Implemented by 01149b0de243bf07d94920d885b8144e7a680719.
